pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-2'
  }

  stages {
    stage('Verificar estructura de archivos') {
      steps {
        sh 'ls -R'
      }
    }

    stage('Instalar dependencias Node.js') {
      steps {
        dir('terraform/lambda') {
          sh 'npm install'
        }
      }
    }

    stage('Compilar y empaquetar Lambda Java') {
      steps {
        sh 'mvn clean package -U'
        sh 'cp target/ms-preventista-0.0.1.jar terraform/java/'
      }
    }

    stage('Empaquetar Lambda Node.js') {
      steps {
        dir('terraform/lambda') {
          sh 'zip lambda.zip lambda-handler.js'
        }
      }
    }

    stage('Desplegar con Terraform') {
      steps {
        dir('terraform') {
          sh 'terraform init'
          sh 'terraform apply -auto-approve'
        }
      }
    }
  }
}
