pipeline {
  agent any

  environment {
    AWS_REGION = 'us-east-2'
  }

  stages {
    stage('Clonar repositorio desde GitHub') {
      steps {
        git credentialsId: 'github-token', url: 'https://github.com/apooo22/proyectoAws.git', branch: 'main'
      }
    }

    stage('Verificar estructura de archivos') {
      steps {
        sh 'ls -R'
      }
    }

    stage('Instalar dependencias Node.js') {
      steps {
        dir('despliegue/terraform/lambda') {
          sh 'npm install'
        }
      }
    }

 stage('Compilar y empaquetar Lambda Java') {
  steps {
    dir('despliegue/terraform/java') {
      sh 'mvn clean package -U'
      sh 'cp target/ms-preventista-0.0.1.jar ../'
    }
  }
}

    stage('Empaquetar Lambda Node.js') {
      steps {
        dir('despliegue/terraform/lambda') {
          sh 'zip lambda.zip lambda-handler.js'
        }
      }
    }

    stage('Desplegar con Terraform') {
      steps {
        dir('despliegue/terraform') {
          sh 'terraform init'
          sh 'terraform apply -auto-approve'
        }
      }
    }
  }
}
